//! Generated bindings for the example snapshot. README snippets compile against this module.

/// Bindings generated by `build.rs` from `schema.json`.
pub mod database {
    rp_supabase_client::include_schema!("database.rs");
}

/// Compiles the rp-supabase-client README snippets.
#[cfg(doctest)]
#[doc = include_str!("../../supabase-client/README.md")]
pub struct ClientReadme;

/// Compiles the rp-supabase-codegen README snippets.
#[cfg(doctest)]
#[doc = include_str!("../../supabase-codegen/README.md")]
pub struct CodegenReadme;
