reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
comment_width = 100
wrap_comments = true
binop_separator = "Back"
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
