name: "Setup Repo Action"
description: "A reusable composite action that setups rust and other common tasks"
inputs:
  toolchain:
    description: "An example input parameter"
    required: false
    default: "nightly-2024-08-25"

runs:
  using: "composite"
  steps:
    - name: Install nightly
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}
        components: "rustfmt,clippy,cargo,llvm-tools-preview"
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
