name: "Setup Repo Action"
description: "A reusable composite action that setups rust and other common tasks"
inputs:
  toolchain:
    description: "Rust toolchain used for workspace verification"
    required: false
    default: "1.99.0"

runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}
        components: "rustfmt,clippy,cargo,llvm-tools-preview"
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
