[net]
git-fetch-with-cli = true

[build]
rustflags = ["-Z", "threads=8", "-Ctarget-cpu=native", "-Zthreads=10"]

[alias]
xtask = "run --package xtask --"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
