[package]
name = "supabase-client"
version = "0.1.0"
edition = "2021"

[dependencies]
supabase-auth.workspace = true
url.workspace = true
reqwest.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
serde.workspace = true
simd-json.workspace = true

[lints]
workspace = true
