[package]
name = "rp-postgrest-error"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true

[lints]
workspace = true
