[package]
name = "rp-postgrest-error"
description = """
strongly typed errors for PostgREST
"""
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
readme = "README.md"

[dependencies]
http.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
