name: deny

on:
  push:
    branches: [main]
    paths: [Cargo.lock]
  pull_request:
    branches: [main]
    paths: [Cargo.lock]

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

concurrency: deny-${{ github.head_ref || github.run_id }}

jobs:
  deny:
    name: deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup repo
        uses: ./.github/actions/setup-repo

      - name: cargo coverage
        run: cargo xtask deny
